


# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 0
  datasource:
    url: jdbc:mysql://localhost:3306/red_packet
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lideng














